import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { App, Button, Card, Col, Collapse, Drawer, Empty, Modal, Progress, Row, Space, Spin, Tabs, Tag, Typography } from 'antd';
import { ArrowLeftOutlined, BookOutlined, FileTextOutlined, MessageOutlined, PlayCircleOutlined, ReloadOutlined, ThunderboltOutlined } from '@ant-design/icons';
import { analyzeKnowledgeBase, deleteDocument, getDocumentObjectUrl, getKnowledgeBaseDetail, KnowledgeBaseDetail, knowledgePointToCard } from '../services/api';
const { Title, Text, Paragraph } = Typography;

const KnowledgeBase: React.FC = () => {
  const { message } = App.useApp();
  const {id}=useParams<{id:string}>(); const navigate=useNavigate(); const [data,setData]=useState<KnowledgeBaseDetail|null>(null); const [loading,setLoading]=useState(true); const [analyzing,setAnalyzing]=useState(false); const [preview,setPreview]=useState<{id:string;name:string;url:string}|null>(null);
  const load=useCallback(()=>{if(!id)return;setLoading(true);getKnowledgeBaseDetail(id).then(setData).catch(()=>message.error('知识库没有加载成功')).finally(()=>setLoading(false));},[id]);
  useEffect(load,[load]);
  if(loading)return <Spin size="large"/>; if(!data)return <Empty description="没有找到这个知识库"/>;
  const analyze=async(documentId?:string,regenerate=false)=>{setAnalyzing(true);try{const result=await analyzeKnowledgeBase(data.id,documentId,regenerate);setData(result.detail);message.success(result.created_points?`整理出 ${result.created_points} 个知识点`:'现有内容已经整理过了');}catch(e:any){message.error(e?.response?.data?.detail||'整理失败，请确认资料已经解析完成');}finally{setAnalyzing(false);}};
  const documentsTab=<div>{data.documents.length?<Row gutter={[14,14]}>{data.documents.map(doc=><Col span={24} key={doc.id}><Card className="paper-card" styles={{body:{padding:18}}}><Row align="middle" gutter={[16,12]}><Col><span style={{width:46,height:54,borderRadius:8,display:'grid',placeItems:'center',background:'#edf6f5',color:'#167d8d',fontSize:22}}><FileTextOutlined/></span></Col><Col flex="auto"><Text strong>{doc.filename}</Text><br/><Space size={6} wrap><Tag color={doc.status==='ready'?'success':doc.status==='failed'?'error':'processing'}>{doc.status==='ready'?'已解析':doc.status==='failed'?'解析失败':'处理中'}</Tag><Text type="secondary">{doc.chunk_count||0} 个片段</Text>{doc.summary&&<Tag bordered={false}>已生成摘要</Tag>}</Space></Col><Col><Space wrap><Button onClick={async()=>{const url=await getDocumentObjectUrl(doc.id);setPreview({id:doc.id,name:doc.filename,url});}}>查看原文</Button><Button icon={<ThunderboltOutlined/>} loading={analyzing} disabled={doc.status!=='ready'} onClick={()=>analyze(doc.id)}>AI 整理</Button><Button danger type="text" onClick={()=>Modal.confirm({title:'删除这份资料？',content:'相关向量和知识点也会被移除。',onOk:async()=>{await deleteDocument(doc.id);load();}})}>删除</Button></Space></Col></Row>{doc.summary&&<Paragraph style={{margin:'14px 0 0',padding:'13px 15px',background:'#f7fafb',borderRadius:10}} ellipsis={{rows:2,expandable:true,symbol:'展开摘要'}}>{doc.summary}</Paragraph>}</Card></Col>)}</Row>:<div className="paper-card empty-guide"><Empty description="还没有学习资料"/><Button type="primary" onClick={()=>navigate(`/upload?workspace=${data.id}`)}>导入资料</Button></div>}</div>;
  const pointsTab=<div>{data.knowledge_points.length?<Collapse ghost items={data.knowledge_points.map((p,index)=>({key:p.id,label:<Space><span style={{fontFamily:'Georgia',color:'#8aa0aa',width:22}}>{String(index+1).padStart(2,'0')}</span><Text strong>{p.title}</Text><Progress percent={Math.round(p.mastery*100)} size="small" style={{width:90}} showInfo={false}/></Space>,extra:<Button size="small" onClick={async e=>{e.stopPropagation();await knowledgePointToCard(p.id);message.success('已加入今日复习卡片');}}>制成卡片</Button>,children:<div style={{padding:'0 8px 14px 34px'}}><Paragraph style={{fontSize:15,lineHeight:1.8}}>{p.explanation||p.summary}</Paragraph><Space wrap>{p.source_heading&&<Tag>{p.source_heading}</Tag>}{p.source_page&&<Tag>第 {p.source_page} 页</Tag>}{p.tags.map(t=><Tag key={t} bordered={false}>{t}</Tag>)}</Space></div>}))}/>:<div className="paper-card empty-guide"><Empty description="让 AI 从资料中提炼核心概念"/><Button type="primary" icon={<ThunderboltOutlined/>} loading={analyzing} onClick={()=>analyze()}>开始整理</Button></div>}</div>;
  const overview=<Row gutter={[20,20]}><Col xs={24} lg={15}><section className="paper-card" style={{padding:24}}><Title level={3}>学习路线</Title>{data.documents.length?<div className="learning-trail" style={{marginTop:22}}>{data.documents.map((doc,i)=><div key={doc.id} style={{position:'relative',paddingBottom:22}}><span className="trail-dot" style={{top:4,borderColor:doc.status==='ready'?'#167d8d':'#b8c6cc'}}/><Text strong>{doc.filename}</Text><br/><Text type="secondary">{doc.summary?doc.summary.slice(0,80):doc.status==='ready'?'等待 AI 整理学习重点':'资料正在解析'}</Text></div>)}</div>:<Empty description="导入资料后，这里会形成学习路线"/>}</section></Col><Col xs={24} lg={9}><section className="soft-panel" style={{padding:24}}><Title level={3}>掌握进度</Title><Progress percent={data.progress} strokeColor="#167d8d"/><Row gutter={[8,18]} style={{marginTop:22}}><Col span={12}><div className="metric-number" style={{fontSize:28,fontWeight:700}}>{data.knowledge_points.length}</div><Text type="secondary">知识点</Text></Col><Col span={12}><div className="metric-number" style={{fontSize:28,fontWeight:700}}>{data.card_count}</div><Text type="secondary">复习卡片</Text></Col><Col span={12}><div className="metric-number" style={{fontSize:28,fontWeight:700}}>{data.documents.length}</div><Text type="secondary">学习资料</Text></Col><Col span={12}><div className="metric-number" style={{fontSize:28,fontWeight:700}}>{data.quiz_count}</div><Text type="secondary">练习题</Text></Col></Row></section></Col></Row>;
  return <div><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/knowledge')}>返回知识库</Button><Row justify="space-between" align="bottom" gutter={[16,16]} style={{marginTop:14}}><Col flex="auto"><Space><Tag color={data.accent_color}>{data.domain}</Tag><Text type="secondary">{data.documents.length} 份资料</Text></Space><Title className="page-title" level={1} style={{marginTop:8}}>{data.name}</Title><p className="page-lead">{data.learning_goal||data.description||'为这个知识库写下一个清晰的学习目标。'}</p></Col><Col><Space wrap><Button icon={<ThunderboltOutlined/>} loading={analyzing} onClick={()=>analyze()}>整理全部资料</Button><Button type="primary" icon={<PlayCircleOutlined/>} onClick={()=>navigate(`/learn?workspace=${data.id}`)}>开始学习</Button></Space></Col></Row><Tabs style={{marginTop:28}} size="large" items={[{key:'overview',label:'学习概览',children:overview},{key:'points',label:`知识点 ${data.knowledge_points.length}`,children:pointsTab},{key:'documents',label:`资料 ${data.documents.length}`,children:documentsTab}]}/><Drawer width="min(900px, 92vw)" title={preview?.name} open={!!preview} onClose={()=>{if(preview)URL.revokeObjectURL(preview.url);setPreview(null)}} extra={preview&&<Button href={preview.url} download={preview.name}>下载</Button>} styles={{body:{padding:0}}}>{preview&&<iframe title={preview.name} src={preview.url} style={{width:'100%',height:'calc(100vh - 62px)',border:0}}/>}</Drawer></div>;
};
export default KnowledgeBase;
